AuctionsBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.AuctionBucket.name}
    LifecycleConfiguration:
      Rules:
        - Id: ExpirePicture
          Status: Enabled
          ExpirationInDays: 1

AuctionsBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref AuctionsBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: '*'
          Action:
            - S3:GetObject
          Resource: arn:aws:s3:::${self:custom.AuctionBucket.name}/*